# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180302_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_article', to='home.Tag', verbose_name='标签'),
        ),
    ]
