# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-16 15:02
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180312_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(default='', verbose_name='文章内容'),
        ),
    ]
