# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-16 15:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180416_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(default='', verbose_name='文章内容'),
        ),
    ]
