# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_auto_20180312_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField(default=0, verbose_name='父评论id')),
                ('nick_name', models.CharField(max_length=20, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('text', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
